apiVersion: batch/v1
kind: Job
metadata: 
  name: asusdownloader
spec: 
  completionMode: Indexed
  completions: 1784
  parallelism: 500
  template: 
    spec: 
      containers: 
        - image: "tejeshreddy/asusdownloader:v1"
          imagePullPolicy: Always
          name: asusdownloader
          resources: 
            limits: 
              cpu: "1"
              memory: 64Gi
            requests: 
              cpu: "0.5"
              memory: 4Gi
          volumeMounts: 
            - mountPath: /shared
              name: nfs-shared
      restartPolicy: Never
      volumes: 
        - name: nfs-shared
          persistentVolumeClaim: 
            claimName: nfs
